version: '3'
services:
  php:
    build: 
      context: ../
      dockerfile: .docker/php-fpm/Dockerfile
    container_name: microbpm_php
    restart: unless-stopped
    networks:
      - api
      - db
    links:
      - db
    volumes:
      - ../api/:/var/www/html
      
  webserver:
    build: 
      context: ../
      dockerfile: .docker/nginx/Dockerfile
    container_name: microbpm_webserver
    restart: unless-stopped
    networks:
      - api
    ports:
      - "80:80"
    links:
      - php

  db:
    image: mysql:8
    container_name: microbpm_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ${MYSQL_VOLUME_FOLDER}:/var/lib/mysql

networks:
  api:
    driver: bridge
  db:
    driver: bridge
